# Server address
server.address=localhost

# Server port
server.port=443

# Gateway instance
gateway.instance=1

# UrlQueue instance
urlqueue.instance=1

# Number of barrels
barrel.number=1

# Number of downloaders
downloader.number=1

# SSL Configuration
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=maezinha
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot